/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as MisComprasRouteImport } from './routes/mis-compras'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIdRouteImport } from './routes/productos.$id'
import { Route as MisComprasIdRouteImport } from './routes/mis-compras.$id'
import { Route as AdminTopVentasRouteImport } from './routes/admin.top-ventas'
import { Route as AdminStockBajoRouteImport } from './routes/admin.stock-bajo'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminFacturacionRouteImport } from './routes/admin.facturacion'
import { Route as AdminCuponesRouteImport } from './routes/admin.cupones'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const MisComprasRoute = MisComprasRouteImport.update({
  id: '/mis-compras',
  path: '/mis-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIdRoute = ProductosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductosRoute,
} as any)
const MisComprasIdRoute = MisComprasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MisComprasRoute,
} as any)
const AdminTopVentasRoute = AdminTopVentasRouteImport.update({
  id: '/top-ventas',
  path: '/top-ventas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockBajoRoute = AdminStockBajoRouteImport.update({
  id: '/stock-bajo',
  path: '/stock-bajo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturacionRoute = AdminFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponesRoute = AdminCuponesRouteImport.update({
  id: '/cupones',
  path: '/cupones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/mis-compras': typeof MisComprasRouteWithChildren
  '/productos': typeof ProductosRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/stock-bajo': typeof AdminStockBajoRoute
  '/admin/top-ventas': typeof AdminTopVentasRoute
  '/mis-compras/$id': typeof MisComprasIdRoute
  '/productos/$id': typeof ProductosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/mis-compras': typeof MisComprasRouteWithChildren
  '/productos': typeof ProductosRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/stock-bajo': typeof AdminStockBajoRoute
  '/admin/top-ventas': typeof AdminTopVentasRoute
  '/mis-compras/$id': typeof MisComprasIdRoute
  '/productos/$id': typeof ProductosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/mis-compras': typeof MisComprasRouteWithChildren
  '/productos': typeof ProductosRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/stock-bajo': typeof AdminStockBajoRoute
  '/admin/top-ventas': typeof AdminTopVentasRoute
  '/mis-compras/$id': typeof MisComprasIdRoute
  '/productos/$id': typeof ProductosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrito'
    | '/checkout'
    | '/mis-compras'
    | '/productos'
    | '/admin/categorias'
    | '/admin/cupones'
    | '/admin/facturacion'
    | '/admin/productos'
    | '/admin/stock-bajo'
    | '/admin/top-ventas'
    | '/mis-compras/$id'
    | '/productos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrito'
    | '/checkout'
    | '/mis-compras'
    | '/productos'
    | '/admin/categorias'
    | '/admin/cupones'
    | '/admin/facturacion'
    | '/admin/productos'
    | '/admin/stock-bajo'
    | '/admin/top-ventas'
    | '/mis-compras/$id'
    | '/productos/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrito'
    | '/checkout'
    | '/mis-compras'
    | '/productos'
    | '/admin/categorias'
    | '/admin/cupones'
    | '/admin/facturacion'
    | '/admin/productos'
    | '/admin/stock-bajo'
    | '/admin/top-ventas'
    | '/mis-compras/$id'
    | '/productos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRoute
  MisComprasRoute: typeof MisComprasRouteWithChildren
  ProductosRoute: typeof ProductosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-compras': {
      id: '/mis-compras'
      path: '/mis-compras'
      fullPath: '/mis-compras'
      preLoaderRoute: typeof MisComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$id': {
      id: '/productos/$id'
      path: '/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof ProductosIdRouteImport
      parentRoute: typeof ProductosRoute
    }
    '/mis-compras/$id': {
      id: '/mis-compras/$id'
      path: '/$id'
      fullPath: '/mis-compras/$id'
      preLoaderRoute: typeof MisComprasIdRouteImport
      parentRoute: typeof MisComprasRoute
    }
    '/admin/top-ventas': {
      id: '/admin/top-ventas'
      path: '/top-ventas'
      fullPath: '/admin/top-ventas'
      preLoaderRoute: typeof AdminTopVentasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock-bajo': {
      id: '/admin/stock-bajo'
      path: '/stock-bajo'
      fullPath: '/admin/stock-bajo'
      preLoaderRoute: typeof AdminStockBajoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturacion': {
      id: '/admin/facturacion'
      path: '/facturacion'
      fullPath: '/admin/facturacion'
      preLoaderRoute: typeof AdminFacturacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupones': {
      id: '/admin/cupones'
      path: '/cupones'
      fullPath: '/admin/cupones'
      preLoaderRoute: typeof AdminCuponesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminCuponesRoute: typeof AdminCuponesRoute
  AdminFacturacionRoute: typeof AdminFacturacionRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminStockBajoRoute: typeof AdminStockBajoRoute
  AdminTopVentasRoute: typeof AdminTopVentasRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminCuponesRoute: AdminCuponesRoute,
  AdminFacturacionRoute: AdminFacturacionRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminStockBajoRoute: AdminStockBajoRoute,
  AdminTopVentasRoute: AdminTopVentasRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MisComprasRouteChildren {
  MisComprasIdRoute: typeof MisComprasIdRoute
}

const MisComprasRouteChildren: MisComprasRouteChildren = {
  MisComprasIdRoute: MisComprasIdRoute,
}

const MisComprasRouteWithChildren = MisComprasRoute._addFileChildren(
  MisComprasRouteChildren,
)

interface ProductosRouteChildren {
  ProductosIdRoute: typeof ProductosIdRoute
}

const ProductosRouteChildren: ProductosRouteChildren = {
  ProductosIdRoute: ProductosIdRoute,
}

const ProductosRouteWithChildren = ProductosRoute._addFileChildren(
  ProductosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRoute,
  MisComprasRoute: MisComprasRouteWithChildren,
  ProductosRoute: ProductosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
