/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MisComprasRouteImport } from './routes/mis-compras'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosIdRouteImport } from './routes/productos.$id'
import { Route as ComprasIdRouteImport } from './routes/compras.$id'
import { Route as AdminTopRouteImport } from './routes/admin.top'
import { Route as AdminStockBajoRouteImport } from './routes/admin.stock-bajo'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminDevolucionesRouteImport } from './routes/admin.devoluciones'
import { Route as AdminCuponesRouteImport } from './routes/admin.cupones'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'

const MisComprasRoute = MisComprasRouteImport.update({
  id: '/mis-compras',
  path: '/mis-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIdRoute = ProductosIdRouteImport.update({
  id: '/productos/$id',
  path: '/productos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasIdRoute = ComprasIdRouteImport.update({
  id: '/compras/$id',
  path: '/compras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopRoute = AdminTopRouteImport.update({
  id: '/admin/top',
  path: '/admin/top',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockBajoRoute = AdminStockBajoRouteImport.update({
  id: '/admin/stock-bajo',
  path: '/admin/stock-bajo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/admin/reportes',
  path: '/admin/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/admin/productos',
  path: '/admin/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevolucionesRoute = AdminDevolucionesRouteImport.update({
  id: '/admin/devoluciones',
  path: '/admin/devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuponesRoute = AdminCuponesRouteImport.update({
  id: '/admin/cupones',
  path: '/admin/cupones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/mis-compras': typeof MisComprasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/devoluciones': typeof AdminDevolucionesRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/stock-bajo': typeof AdminStockBajoRoute
  '/admin/top': typeof AdminTopRoute
  '/compras/$id': typeof ComprasIdRoute
  '/productos/$id': typeof ProductosIdRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/mis-compras': typeof MisComprasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/devoluciones': typeof AdminDevolucionesRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/stock-bajo': typeof AdminStockBajoRoute
  '/admin/top': typeof AdminTopRoute
  '/compras/$id': typeof ComprasIdRoute
  '/productos/$id': typeof ProductosIdRoute
  '/productos': typeof ProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/mis-compras': typeof MisComprasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/devoluciones': typeof AdminDevolucionesRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/stock-bajo': typeof AdminStockBajoRoute
  '/admin/top': typeof AdminTopRoute
  '/compras/$id': typeof ComprasIdRoute
  '/productos/$id': typeof ProductosIdRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrito'
    | '/mis-compras'
    | '/admin/categorias'
    | '/admin/cupones'
    | '/admin/devoluciones'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/stock-bajo'
    | '/admin/top'
    | '/compras/$id'
    | '/productos/$id'
    | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/mis-compras'
    | '/admin/categorias'
    | '/admin/cupones'
    | '/admin/devoluciones'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/stock-bajo'
    | '/admin/top'
    | '/compras/$id'
    | '/productos/$id'
    | '/productos'
  id:
    | '__root__'
    | '/'
    | '/carrito'
    | '/mis-compras'
    | '/admin/categorias'
    | '/admin/cupones'
    | '/admin/devoluciones'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/stock-bajo'
    | '/admin/top'
    | '/compras/$id'
    | '/productos/$id'
    | '/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarritoRoute: typeof CarritoRoute
  MisComprasRoute: typeof MisComprasRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminCuponesRoute: typeof AdminCuponesRoute
  AdminDevolucionesRoute: typeof AdminDevolucionesRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminStockBajoRoute: typeof AdminStockBajoRoute
  AdminTopRoute: typeof AdminTopRoute
  ComprasIdRoute: typeof ComprasIdRoute
  ProductosIdRoute: typeof ProductosIdRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mis-compras': {
      id: '/mis-compras'
      path: '/mis-compras'
      fullPath: '/mis-compras'
      preLoaderRoute: typeof MisComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$id': {
      id: '/productos/$id'
      path: '/productos/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof ProductosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/$id': {
      id: '/compras/$id'
      path: '/compras/$id'
      fullPath: '/compras/$id'
      preLoaderRoute: typeof ComprasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/top': {
      id: '/admin/top'
      path: '/admin/top'
      fullPath: '/admin/top'
      preLoaderRoute: typeof AdminTopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock-bajo': {
      id: '/admin/stock-bajo'
      path: '/admin/stock-bajo'
      fullPath: '/admin/stock-bajo'
      preLoaderRoute: typeof AdminStockBajoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/admin/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/devoluciones': {
      id: '/admin/devoluciones'
      path: '/admin/devoluciones'
      fullPath: '/admin/devoluciones'
      preLoaderRoute: typeof AdminDevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupones': {
      id: '/admin/cupones'
      path: '/admin/cupones'
      fullPath: '/admin/cupones'
      preLoaderRoute: typeof AdminCuponesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarritoRoute: CarritoRoute,
  MisComprasRoute: MisComprasRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminCuponesRoute: AdminCuponesRoute,
  AdminDevolucionesRoute: AdminDevolucionesRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminStockBajoRoute: AdminStockBajoRoute,
  AdminTopRoute: AdminTopRoute,
  ComprasIdRoute: ComprasIdRoute,
  ProductosIdRoute: ProductosIdRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
